-- MySQL Script generated by MySQL Workbench
-- Mon Dec 26 12:14:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8;
USE mydb;

-- -----------------------------------------------------
-- Table Staff
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Staff
(
    StaffID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (StaffID)
);

-- -----------------------------------------------------
-- Table Game
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Game
(
    gameID    INT          NOT NULL AUTO_INCREMENT,
    game_name VARCHAR(255) NULL,
    PRIMARY KEY (gameID)
);

-- -----------------------------------------------------
-- Table Team
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Team
(
    TeamID      INT          NOT NULL AUTO_INCREMENT,
    team_name   VARCHAR(255) NULL,
    Game_gameID INT          NULL,
    PRIMARY KEY (TeamID),
    INDEX fk_Team_Game1_idx (Game_gameID ASC) VISIBLE,
    CONSTRAINT fk_Team_Game1
        FOREIGN KEY (Game_gameID)
            REFERENCES Game (gameID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table Player
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Player
(
    playerID       INT          NOT NULL AUTO_INCREMENT,
    firstname      VARCHAR(255) NULL,
    lastname       VARCHAR(255) NULL,
    nickname       VARCHAR(255) NULL,
    street_address VARCHAR(255) NULL,
    zipcode        INT          NULL,
    country        VARCHAR(255) NULL,
    e_mail         VARCHAR(255) NULL,
    Staff_StaffID  INT          NULL,
    Game_gameID    INT          NULL,
    Team_TeamID    INT          NULL,
    PRIMARY KEY (playerID),
    INDEX fk_Player_Staff_idx (Staff_StaffID ASC) VISIBLE,
    INDEX fk_Player_Game1_idx (Game_gameID ASC) VISIBLE,
    INDEX fk_Player_Team1_idx (Team_TeamID ASC) VISIBLE,
    CONSTRAINT fk_Player_Staff
        FOREIGN KEY (Staff_StaffID)
            REFERENCES Staff (StaffID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
    CONSTRAINT fk_Player_Game1
        FOREIGN KEY (Game_gameID)
            REFERENCES Game (gameID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
    CONSTRAINT fk_Player_Team1
        FOREIGN KEY (Team_TeamID)
            REFERENCES Team (TeamID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table Matches
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Matches
(
    matchID INT     NOT NULL AUTO_INCREMENT,
    isDone  TINYINT NULL,
    PRIMARY KEY (matchID)
);

-- -----------------------------------------------------
-- Table player_matches
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS player_matches
(
    idplayer_Matches INT NOT NULL,
    Player_playerID  INT NULL,
    Matches_matchID  INT NULL,
    PRIMARY KEY (idplayer_Matches),
    INDEX fk_player_Matches_Player1_idx (Player_playerID ASC) VISIBLE,
    INDEX fk_player_Matches_Matches1_idx (Matches_matchID ASC) VISIBLE,
    CONSTRAINT fk_player_Matches_Player1
        FOREIGN KEY (Player_playerID)
            REFERENCES Player (playerID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
    CONSTRAINT fk_player_Matches_Matches1
        FOREIGN KEY (Matches_matchID)
            REFERENCES Matches (matchID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table team_matches
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS team_matches
(
    idteam_matches  INT NOT NULL,
    Team_TeamID     INT NULL,
    Matches_matchID INT NULL,
    PRIMARY KEY (idteam_matches),
    INDEX fk_team_matches_Team1_idx (Team_TeamID ASC) VISIBLE,
    INDEX fk_team_matches_Matches1_idx (Matches_matchID ASC) VISIBLE,
    CONSTRAINT fk_team_matches_Team1
        FOREIGN KEY (Team_TeamID)
            REFERENCES Team (TeamID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
    CONSTRAINT fk_team_matches_Matches1
        FOREIGN KEY (Matches_matchID)
            REFERENCES Matches (matchID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION
)

-- SET SQL_MODE = @OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
